services:
  - type: worker
    name: youtube-mp3-bot
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        value: "7871806593:AAF0d3grjeT7Is9PabfZYwKUTj77FCqkksU" 